spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:farmdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password